# Generated by Django 3.2 on 2021-04-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name_plural': "tem's"},
        ),
    ]
