# Generated by Django 3.2 on 2021-04-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_tema_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tema')),
            ],
            options={
                'verbose_name_plural': 'razdely',
            },
        ),
    ]
