# Generated by Django 3.2 on 2021-04-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_razdel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razdel',
            old_name='topic',
            new_name='tema',
        ),
    ]
